### ISSUE TITLE
Plan to extend Drawing Manger public API?

### ISSUE THREAD

**Issue by TrangNguyen** [cristiandley/react-gl-maps#7]
Is there a reason why only getDrawingMode() is exposed as [public API](https://github.com/cristiandley/react-gl-maps/blob/master/src/DrawingManager.js)? Is it a bad practice to expose other methods, like setDrawingMode(), setOptions(), etc, basically complete reference to drawingManager?
I can't manage to set up the project locally (on Mac OSX, npm 4, without Docker) either with tomchentw or this repo, so I can't make any PR either.
Thanks

**Comment by cristiandley** [comment]
@TrangNguyen please update this issue, the second part is a reference to your new one https://github.com/cristiandley/react-gl-maps/issues/8 

We are trying to figure a new package/repo desing as we are disscusing here https://github.com/cristiandley/react-gl-maps/issues/6 

I believe is a bad thing having the complete reference exposed. This should be enhaced.

**Comment by TrangNguyen** [comment]
Thanks for your quick response.
I tried to set drawingMode of the Drawing Manger over a condition like this 

```
<DrawingManager
   drawingMode={this.state.drawingMode}
   onPolygoncomplete={this.handlePolygonComplete}
    ... 
   />
```

which works but it doesn't have the whole control of the drawn objects so on scrolling/zooming while drawing, the line is broken and I can't access them. I attached a pix here to illustrate, the left line and shapes were accidentally drawn with scrolling/zooming. The right shape - the one on the right and that's the only polygon I have access to on `onPolygoncomplete` event. If I clear the map, the first baddies would be there.
![bildschirmfoto 2016-05-26 um 14 48 17](https://cloud.githubusercontent.com/assets/2684809/15575019/fd19b26c-2350-11e6-8bdc-b589016edb36.png)

**Comment by TrangNguyen** [comment]
I've found a way to control the scrolling/zooming while drawing. Basically conditionally render the DrawingManager instead of always including it as child component to the <Map>. Thanks.

**Comment by cristiandley** [comment]
@TrangNguyen Great!

If your idea is helpul i encourage you to make PR.

Thank you!

**Comment by davidpelayo** [comment]
@TrangNguyen can you post an jsbin/plunkr example to look at how does the idea look like? Thanks!
